# adapted from https://github.com/r-lib/actions/tree/master/examples
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: R-test-that

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install packages
        run: |
          R -e 'install.packages("testthat")'
          R -e 'install.packages("tidyverse")'
          R -e 'install.packages("readit")'
          R -e 'install.packages("tidyjson")'
          R -e 'install.packages("R2HTML")'
          R -e 'install.packages("jsonlite")'
         
      - name: Build site
        run: Rscript -e 'bookdown::render_book("index.Rmd", quiet = TRUE)'
        run: |
          library(testthat)
          testthat::test_dir(testthat::test_path())
